packages:
  - packages/*

catalog:
  better-sqlite3: ^12.5.0
  esbuild: ^0.27.1
  typescript: ^5.8.3
  typescript-eslint: ^8.39.0
  lodash: ^4.17.21
  "@types/lodash": ^4.17.21
  "@types/node": ^24.10.4
  jest: ^30.2.0
  ts-jest: ^29.4.6

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - better-sqlite3
  - esbuild
  - keytar
  - unrs-resolver
