packages:
  - packages/*

catalog:
  '@types/lodash': ^4.17.21
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  better-sqlite3: ^12.5.0
  esbuild: ^0.27.1
  jest: ^30.2.0
  lodash: ^4.17.21
  react: ^19.2.3
  react-dom: ^19.2.3
  ts-jest: ^29.4.6
  typescript: ^5.9.3
  typescript-eslint: ^8.50.0

ignoredBuiltDependencies:
  - sqlite3

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - better-sqlite3
  - esbuild
  - keytar
  - nx
  - sqlite3
  - unrs-resolver
