ALTER TABLE weights 
    ADD COLUMN IF NOT EXISTS tag VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS description TEXT NULL;

ALTER TABLE weights 
    ALTER COLUMN htime SET DEFAULT 0,
    ALTER COLUMN htime SET NOT NULL;