
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  PrismaClientKnownRequestError,
  PrismaClientUnknownRequestError,
  PrismaClientRustPanicError,
  PrismaClientInitializationError,
  PrismaClientValidationError,
  getPrismaClient,
  sqltag,
  empty,
  join,
  raw,
  skip,
  Decimal,
  Debug,
  objectEnumValues,
  makeStrictEnum,
  Extensions,
  warnOnce,
  defineDmmfProperty,
  Public,
  getRuntime,
  createParam,
} = require('./runtime/wasm-engine-edge.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.1
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.1",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = PrismaClientKnownRequestError;
Prisma.PrismaClientUnknownRequestError = PrismaClientUnknownRequestError
Prisma.PrismaClientRustPanicError = PrismaClientRustPanicError
Prisma.PrismaClientInitializationError = PrismaClientInitializationError
Prisma.PrismaClientValidationError = PrismaClientValidationError
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = sqltag
Prisma.empty = empty
Prisma.join = join
Prisma.raw = raw
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = Extensions.getExtensionContext
Prisma.defineExtension = Extensions.defineExtension

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}





/**
 * Enums
 */
exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.NoteScalarFieldEnum = {
  id: 'id',
  fname: 'fname',
  title: 'title',
  updated: 'updated',
  created: 'created',
  stub: 'stub',
  dVaultId: 'dVaultId'
};

exports.Prisma.DVaultScalarFieldEnum = {
  id: 'id',
  name: 'name',
  fsPath: 'fsPath',
  wsRoot: 'wsRoot'
};

exports.Prisma.WorkspaceScalarFieldEnum = {
  wsRoot: 'wsRoot',
  prismaSchemaVersion: 'prismaSchemaVersion'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  Note: 'Note',
  DVault: 'DVault',
  Workspace: 'Workspace'
};
/**
 * Create the Client
 */
const config = {
  "generator": {
    "name": "client",
    "provider": {
      "fromEnvVar": null,
      "value": "prisma-client-js"
    },
    "output": {
      "value": "D:\\ws\\repos\\SailZen\\packages\\engine-server\\src\\drivers\\generated-prisma-client",
      "fromEnvVar": null
    },
    "config": {
      "engineType": "library"
    },
    "binaryTargets": [
      {
        "fromEnvVar": null,
        "value": "windows",
        "native": true
      }
    ],
    "previewFeatures": [],
    "sourceFilePath": "D:\\ws\\repos\\SailZen\\packages\\engine-server\\prisma\\schema.prisma",
    "isCustomOutput": true
  },
  "relativeEnvPaths": {
    "rootEnvPath": null
  },
  "relativePath": "../../../prisma",
  "clientVersion": "6.19.1",
  "engineVersion": "c2990dca591cba766e3b7ef5d9e8a84796e47ab7",
  "datasourceNames": [
    "db"
  ],
  "activeProvider": "sqlite",
  "postinstall": false,
  "inlineDatasources": {
    "db": {
      "url": {
        "fromEnvVar": null,
        "value": "file:./dev.db"
      }
    }
  },
  "inlineSchema": "generator client {\n  provider      = \"prisma-client-js\"\n  binaryTargets = [\"native\"]\n  output        = \"./../src/drivers/generated-prisma-client\"\n}\n\ndatasource db {\n  provider = \"sqlite\"\n  url      = \"file:./dev.db\"\n}\n\nmodel Note {\n  id       String   @id\n  fname    String?\n  title    String?\n  vault    DVault   @relation(fields: [dVaultId], references: [id])\n  updated  Int?\n  created  Int?\n  stub     Boolean?\n  // anchors      Unsupported(\"json\")?\n  // desc         String?\n  // links        Unsupported(\"json\")?\n  dVaultId Int\n\n  @@index([id], map: \"idx_notes_id\")\n}\n\nmodel DVault {\n  id        Int       @id @default(autoincrement())\n  name      String?   @unique\n  fsPath    String\n  wsRoot    String\n  workspace Workspace @relation(fields: [wsRoot], references: [wsRoot], onDelete: Cascade)\n  Note      Note[]\n\n  @@unique([wsRoot, fsPath])\n}\n\nmodel Workspace {\n  wsRoot              String   @id @unique\n  prismaSchemaVersion Int\n  vaults              DVault[]\n}\n",
  "inlineSchemaHash": "41e82a28773808982d62822653374581e34dca9cab20730078c1706d9927c869",
  "copyEngine": true
}
config.dirname = '/'

config.runtimeDataModel = JSON.parse("{\"models\":{\"Note\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"fname\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"title\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"vault\",\"kind\":\"object\",\"type\":\"DVault\",\"relationName\":\"DVaultToNote\"},{\"name\":\"updated\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"created\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"stub\",\"kind\":\"scalar\",\"type\":\"Boolean\"},{\"name\":\"dVaultId\",\"kind\":\"scalar\",\"type\":\"Int\"}],\"dbName\":null},\"DVault\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"name\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"fsPath\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"wsRoot\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"workspace\",\"kind\":\"object\",\"type\":\"Workspace\",\"relationName\":\"DVaultToWorkspace\"},{\"name\":\"Note\",\"kind\":\"object\",\"type\":\"Note\",\"relationName\":\"DVaultToNote\"}],\"dbName\":null},\"Workspace\":{\"fields\":[{\"name\":\"wsRoot\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"prismaSchemaVersion\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"vaults\",\"kind\":\"object\",\"type\":\"DVault\",\"relationName\":\"DVaultToWorkspace\"}],\"dbName\":null}},\"enums\":{},\"types\":{}}")
defineDmmfProperty(exports.Prisma, config.runtimeDataModel)
config.engineWasm = {
  getRuntime: async () => require('./query_engine_bg.js'),
  getQueryEngineWasmModule: async () => {
    const loader = (await import('#wasm-engine-loader')).default
    const engine = (await loader).default
    return engine
  }
}
config.compilerWasm = undefined

config.injectableEdgeEnv = () => ({
  parsed: {}
})

if (typeof globalThis !== 'undefined' && globalThis['DEBUG'] || typeof process !== 'undefined' && process.env && process.env.DEBUG || undefined) {
  Debug.enable(typeof globalThis !== 'undefined' && globalThis['DEBUG'] || typeof process !== 'undefined' && process.env && process.env.DEBUG || undefined)
}

const PrismaClient = getPrismaClient(config)
exports.PrismaClient = PrismaClient
Object.assign(exports, Prisma)

